a=int(input('a='))
b=int(input('b='))
c=int(input('c='))
d=int(input('d='))
Tong= float(a+b+c+d)
TBC= float(Tong/4)
print('Tong=', round(Tong,1), sep='')
print('Trung binh cong=', round(TBC,1), sep='')