HoTen=input('Ho ten: ')
SoNgayCong=int(input('So ngay cong: '))
DonGiaNgayCong=int(input('Don gia ngay cong: '))
HeSoPhuCap=float(input('He so phu cap: '))
TamUng=int(input('Tam ung: '))
Luong= float(DonGiaNgayCong*SoNgayCong*HeSoPhuCap)
ThucLinh= float(Luong-TamUng)
print('Nhan vien', HoTen, end=', ')
print('Co tien Luong=', end='')
print(Luong, end=', ')
print('Tam ung=', end='')
print(TamUng, 'va Thuc linh=', end='')
print(ThucLinh)